# Copyright (c) 2026 Neutron Emulation, LLC. MIT licensed.
"""
Debug information collection for Mesen .dbg file generation.

Collects source file references, segments, spans, line mappings, symbols, and
scopes during code generation for output in cc65-compatible .dbg format.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, TYPE_CHECKING
import os

if TYPE_CHECKING:
    from r65.compiler.errors import SourceLocation


@dataclass
class DbgFile:
    """Source file entry for debug info."""
    id: int
    name: str


@dataclass
class DbgSegment:
    """Memory segment (bank) for debug info."""
    id: int
    name: str
    start: int      # Start address in CPU address space
    size: int       # Size in bytes
    bank: int       # Bank number
    ooffs: int      # Output file offset
    addrsize: str = "absolute"
    seg_type: str = "ro"  # "ro" for ROM or "rw" for RAM


@dataclass
class DbgSpan:
    """Contiguous code/data region within a segment."""
    id: int
    seg_id: int
    start: int      # Offset within segment
    size: int


@dataclass
class DbgLine:
    """Source line to address mapping."""
    id: int
    file_id: int
    line: int
    line_type: int  # 0=asm, 1=external/C, 2=macro
    span_ids: List[int] = field(default_factory=list)


@dataclass
class DbgSymbol:
    """Symbol (label or constant) for debug info."""
    id: int
    name: str
    value: int
    seg_id: Optional[int]
    sym_type: str   # "lab" (label), "equ" (equate), "imp" (import)
    size: int = 0
    scope_id: Optional[int] = None


@dataclass
class DbgScope:
    """Scope (function or block) for debug info."""
    id: int
    name: str
    scope_type: str  # "scope", "global", "module", "struct", "enum"
    size: int
    span_ids: List[int] = field(default_factory=list)
    parent_id: Optional[int] = None
    sym_id: Optional[int] = None  # Associated symbol ID


class DebugInfoCollector:
    """
    Collects debug information during code generation.

    Tracks source files, segments, spans, line mappings, symbols, and scopes
    to generate a complete debug info file for source-level debugging.
    """

    def __init__(self):
        self.files: Dict[str, DbgFile] = {}
        self.segments: List[DbgSegment] = []
        self.spans: List[DbgSpan] = []
        self.lines: List[DbgLine] = []
        self.symbols: List[DbgSymbol] = []
        self.scopes: List[DbgScope] = []
        self._next_file_id = 0
        self._next_span_id = 0
        self._next_line_id = 0
        self._next_sym_id = 0
        self._next_scope_id = 0

    def get_or_create_file(self, path: str) -> DbgFile:
        """
        Get existing file entry or create new one.

        Normalizes paths to absolute paths for consistent source file lookup.
        Special paths (like macro expansions) are preserved as-is.

        Args:
            path: Source file path

        Returns:
            DbgFile entry for this path
        """
        # Normalize to absolute path unless it's a special path (e.g., <macro:...>)
        if not path.startswith('<'):
            path = os.path.abspath(path)

        if path not in self.files:
            self.files[path] = DbgFile(self._next_file_id, path)
            self._next_file_id += 1
        return self.files[path]

    def add_segment(self, name: str, start: int, size: int,
                    bank: int, ooffs: int, seg_type: str = "ro") -> DbgSegment:
        """
        Add a memory segment.

        Args:
            name: Segment name (e.g., "BANK0")
            start: Start address in CPU space
            size: Size in bytes
            bank: Bank number
            ooffs: Output file offset
            seg_type: "ro" for ROM or "rw" for RAM

        Returns:
            Created DbgSegment
        """
        seg = DbgSegment(
            id=len(self.segments),
            name=name,
            start=start,
            size=size,
            bank=bank,
            ooffs=ooffs,
            addrsize="absolute",
            seg_type=seg_type
        )
        self.segments.append(seg)
        return seg

    def add_span(self, seg_id: int, start: int, size: int) -> DbgSpan:
        """
        Add a code/data span within a segment.

        Args:
            seg_id: Parent segment ID
            start: Start offset within segment
            size: Size in bytes

        Returns:
            Created DbgSpan
        """
        span = DbgSpan(self._next_span_id, seg_id, start, size)
        self._next_span_id += 1
        self.spans.append(span)
        return span

    def add_line(self, file_id: int, line: int, span_ids: List[int],
                 line_type: int = 0) -> DbgLine:
        """
        Add a source line mapping.

        Args:
            file_id: Source file ID
            line: Line number (1-indexed)
            span_ids: List of span IDs generated by this line
            line_type: 0=asm, 1=external/C, 2=macro

        Returns:
            Created DbgLine
        """
        line_entry = DbgLine(self._next_line_id, file_id, line, line_type, span_ids)
        self._next_line_id += 1
        self.lines.append(line_entry)
        return line_entry

    def add_symbol(self, name: str, value: int, seg_id: Optional[int],
                   sym_type: str, size: int = 0,
                   scope_id: Optional[int] = None) -> DbgSymbol:
        """
        Add a symbol (label or constant).

        Args:
            name: Symbol name
            value: Symbol value (address for labels, value for constants)
            seg_id: Segment ID (None for absolute symbols)
            sym_type: "lab" (label), "equ" (equate), "imp" (import)
            size: Size in bytes (0 if unknown)
            scope_id: Parent scope ID (None for global)

        Returns:
            Created DbgSymbol
        """
        sym = DbgSymbol(
            id=self._next_sym_id,
            name=name,
            value=value,
            seg_id=seg_id,
            sym_type=sym_type,
            size=size,
            scope_id=scope_id
        )
        self._next_sym_id += 1
        self.symbols.append(sym)
        return sym

    def add_scope(self, name: str, scope_type: str, size: int,
                  span_ids: List[int], parent_id: Optional[int] = None,
                  sym_id: Optional[int] = None) -> DbgScope:
        """
        Add a scope (function or block).

        Args:
            name: Scope name
            scope_type: "scope", "global", "module", "struct", "enum"
            size: Size in bytes
            span_ids: List of span IDs in this scope
            parent_id: Parent scope ID (None for top-level)
            sym_id: Associated symbol ID (for functions)

        Returns:
            Created DbgScope
        """
        scope = DbgScope(
            id=self._next_scope_id,
            name=name,
            scope_type=scope_type,
            size=size,
            span_ids=span_ids,
            parent_id=parent_id,
            sym_id=sym_id
        )
        self._next_scope_id += 1
        self.scopes.append(scope)
        return scope

    def find_or_add_span(self, seg_id: int, start: int, size: int) -> DbgSpan:
        """
        Find existing span or create new one.

        Useful for deduplicating spans when multiple lines map to same code.

        Args:
            seg_id: Parent segment ID
            start: Start offset
            size: Size in bytes

        Returns:
            Existing or new DbgSpan
        """
        for span in self.spans:
            if span.seg_id == seg_id and span.start == start and span.size == size:
                return span
        return self.add_span(seg_id, start, size)

    def get_segment_for_address(self, address: int) -> Optional[DbgSegment]:
        """
        Find segment containing an address.

        Args:
            address: CPU address

        Returns:
            DbgSegment or None if not found
        """
        for seg in self.segments:
            if seg.start <= address < seg.start + seg.size:
                return seg
        return None
