"""
Assembly emitter: generates WLA-DX assembly text.

Provides methods for emitting instructions, labels, comments, and sections
in WLA-DX assembly format for the 65816 processor.

Builds structured AsmNode objects which are converted to assembly text
via emit_nodes().
"""

from typing import List, Optional
from datetime import datetime


# =============================================================================
# Assembly Formatting Constants
# =============================================================================

# Width of section dividers
DIVIDER_WIDTH = 76

# Pre-computed divider strings
SECTION_DIVIDER = "=" * DIVIDER_WIDTH
SUBSECTION_DIVIDER = "-" * DIVIDER_WIDTH

# Column alignment for comments
COMMENT_COLUMN = 32

# Import memory constants (delay import to avoid circular dependency)
def _get_rom_constants():
    from r65.compiler.codegen.constants import (
        LOROM_SLOT_SIZE, LOROM_SLOT_ADDR, HIROM_SLOT_SIZE, HIROM_SLOT_ADDR
    )
    return LOROM_SLOT_SIZE, LOROM_SLOT_ADDR, HIROM_SLOT_SIZE, HIROM_SLOT_ADDR


class AssemblyEmitter:
    """
    Emits WLA-DX assembly code.

    Builds structured AsmNode objects and provides high-level methods
    for generating properly formatted assembly sections and instructions.

    Call get_nodes() to retrieve the structured representation, or
    to_string() to get the final assembly text.
    """

    def __init__(self, source_file: Optional[str] = None):
        """
        Initialize assembly emitter.

        Args:
            source_file: Original R65 source file path (for header)
        """
        self.source_file = source_file or "unknown.r65"

        # Structured node output
        from r65.compiler.codegen.node_emitter import NodeEmitter
        self._node_emitter = NodeEmitter()

    # ========================================================================
    # Low-Level Emission
    # ========================================================================

    def emit_directive(self, text: str):
        """
        Emit a WLA-DX directive (e.g., .65816, .MEMORYMAP).

        Args:
            text: Directive text
        """
        self._node_emitter.emit_raw(text)

    def emit_blank_line(self):
        """Emit a blank line for spacing."""
        self._node_emitter.emit_blank_line()

    def emit_comment(self, text: str):
        """
        Emit a comment line.

        Args:
            text: Comment text (without ; prefix)
        """
        self._node_emitter.emit_comment(text)

    # ========================================================================
    # Section Headers
    # ========================================================================

    def emit_section_header(self, title: str):
        """
        Emit a major section header with divider.

        Example:
            ; ============================================================================
            ; Direct Page Allocations
            ; ============================================================================

        Args:
            title: Section title
        """
        self.emit_comment(SECTION_DIVIDER)
        self.emit_comment(title)
        self.emit_comment(SECTION_DIVIDER)

    def emit_subsection_header(self, title: str):
        """
        Emit a subsection header with dashes.

        Example:
            ; ----------------------------------------------------------------------------
            ; Helper Functions
            ; ----------------------------------------------------------------------------

        Args:
            title: Subsection title
        """
        self.emit_comment(SUBSECTION_DIVIDER)
        self.emit_comment(title)
        self.emit_comment(SUBSECTION_DIVIDER)

    # ========================================================================
    # File Header
    # ========================================================================

    def emit_file_header(self):
        """
        Emit file header with metadata.

        Generated:
            ; ============================================================================
            ; Generated by R65 Compiler
            ; Source: main.r65
            ; Generated: 2026-01-01 14:30:00
            ; Compiler Version: 0.1.0
            ; ============================================================================
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        self.emit_section_header("Generated by R65 Compiler")
        self.emit_comment(f"Source: {self.source_file}")
        self.emit_comment(f"Generated: {now}")
        self.emit_comment("Compiler Version: 0.1.0")
        self.emit_comment(SECTION_DIVIDER)
        self.emit_blank_line()

    # ========================================================================
    # Processor Directives
    # ========================================================================

    def emit_processor_directive(self):
        """
        Emit processor directive for 65816.

        Generated:
            .65816
        """
        self.emit_directive(".65816")
        self.emit_blank_line()

    # ========================================================================
    # Memory Map
    # ========================================================================

    def emit_memory_map(self, rom_type: str = "lorom", banks: int = 1):
        """
        Emit WLA-DX memory map and ROM bank map.

        Args:
            rom_type: "lorom" (32KB banks) or "hirom" (64KB banks)
            banks: Number of ROM banks

        Generated (LoROM):
            .MEMORYMAP
                DEFAULTSLOT 0
                SLOTSIZE $8000
                SLOT 0 $8000
            .ENDME

            .ROMBANKMAP
                BANKSTOTAL 1
                BANKSIZE $8000
                BANKS 1
            .ENDRO
        """
        self.emit_section_header(f"Memory Map ({rom_type.upper()})")

        lorom_size, lorom_addr, hirom_size, hirom_addr = _get_rom_constants()
        if rom_type.lower() == "lorom":
            slot_size = lorom_size
            slot_addr = lorom_addr
        else:  # hirom
            slot_size = hirom_size
            slot_addr = hirom_addr

        # Memory map
        self.emit_directive(".MEMORYMAP")
        self.emit_directive("    DEFAULTSLOT 0")
        self.emit_directive(f"    SLOTSIZE ${slot_size:04X}")
        self.emit_directive(f"    SLOT 0 ${slot_addr:04X}")
        self.emit_directive(".ENDME")
        self.emit_blank_line()

        # ROM bank map
        self.emit_directive(".ROMBANKMAP")
        self.emit_directive(f"    BANKSTOTAL {banks}")
        self.emit_directive(f"    BANKSIZE ${slot_size:04X}")
        self.emit_directive(f"    BANKS {banks}")
        self.emit_directive(".ENDRO")
        self.emit_blank_line()

    # ========================================================================
    # Bank Directives
    # ========================================================================

    def emit_bank_directive(self, bank_num: int, slot: int = 0):
        """
        Emit bank directive and origin.

        Args:
            bank_num: Bank number
            slot: Slot number (usually 0)

        Generated:
            .BANK 0 SLOT 0
            .ORG 0
        """
        self.emit_directive(f".BANK {bank_num} SLOT {slot}")
        self.emit_directive(".ORG 0")
        self.emit_blank_line()

    # ========================================================================
    # Labels
    # ========================================================================

    def emit_label(self, label: str):
        """
        Emit a label.

        Args:
            label: Label name (with or without trailing :)

        Generated:
            label:
        """
        # Strip trailing colon for node emitter (it adds it back)
        label_name = label.rstrip(':')
        self._node_emitter.emit_label(label_name)

    def emit_local_label(self, label: str):
        """
        Emit a local label with indentation.

        Args:
            label: Label name

        Generated:
            __L1:
        """
        self.emit_label(label)

    # ========================================================================
    # Instructions
    # ========================================================================

    def emit_instruction(self, mnemonic: str, operand: Optional[str] = None,
                        comment: Optional[str] = None):
        """
        Emit a single instruction.

        Args:
            mnemonic: Instruction mnemonic (e.g., "LDA", "STA")
            operand: Operand (e.g., "#$42", "$20")
            comment: Optional inline comment

        Generated:
            LDA #$42                ; Load immediate
            STA $20                 ; Store to zero-page
            RTS
        """
        self._node_emitter.emit_instruction(mnemonic, operand, comment)

    # ========================================================================
    # Symbol Definitions
    # ========================================================================

    def emit_define(self, name: str, value: int, comment: Optional[str] = None):
        """
        Emit a .DEFINE directive.

        Args:
            name: Symbol name
            value: Address value
            comment: Optional inline comment

        Generated:
            .DEFINE TEMP $20        ; main.r65:5
        """
        line = f".DEFINE {name} ${value:04X}"

        if comment:
            padding = max(1, COMMENT_COLUMN - len(line))
            line += " " * padding + f"; {comment}"

        self.emit_directive(line)

    def emit_equ(self, name: str, value: int, comment: Optional[str] = None):
        """
        Emit a .EQU directive for constants.

        Args:
            name: Constant name
            value: Constant value
            comment: Optional inline comment

        Generated:
            .EQU SCREEN_WIDTH 256   ; Constant
        """
        line = f".EQU {name} {value}"

        if comment:
            padding = max(1, COMMENT_COLUMN - len(line))
            line += " " * padding + f"; {comment}"

        self.emit_directive(line)

    # ========================================================================
    # Data Directives
    # ========================================================================

    def emit_byte(self, values: List[int]):
        """
        Emit byte data (.DB directive).

        Args:
            values: List of byte values

        Generated:
            .DB $80, $83, $86, $89
        """
        # Format as hex bytes
        hex_values = [f"${v:02X}" for v in values]

        # Emit 8 values per line for readability
        for i in range(0, len(hex_values), 8):
            chunk = hex_values[i:i+8]
            self.emit_directive(f"    .DB {', '.join(chunk)}")

    def emit_word(self, values: List[int]):
        """
        Emit word data (.DW directive).

        Args:
            values: List of word values

        Generated:
            .DW $1234, $5678
        """
        hex_values = [f"${v:04X}" for v in values]

        # Emit 8 values per line
        for i in range(0, len(hex_values), 8):
            chunk = hex_values[i:i+8]
            self.emit_directive(f"    .DW {', '.join(chunk)}")

    def emit_space(self, size: int, fill_value: int = 0):
        """
        Emit space reservation (.DSB directive).

        Args:
            size: Number of bytes to reserve
            fill_value: Fill value (default 0)

        Generated:
            .DSB 256, 0
        """
        self.emit_directive(f"    .DSB {size}, {fill_value}")

    def emit_incbin(self, filepath: str, label: Optional[str] = None):
        """
        Emit binary file inclusion (.INCBIN directive).

        Args:
            filepath: Path to binary file to include
            label: Optional label for the data

        Generated:
            LABEL:
            .INCBIN "path/to/file.bin"
        """
        if label:
            self.emit_label(label)
        self.emit_directive(f'    .INCBIN "{filepath}"')

    # ========================================================================
    # Interrupt Vectors
    # ========================================================================

    def emit_snes_header(self, rom_name="R65 ROM", version=0):
        """
        Emit SNES ROM header using .SNESHEADER directive.

        Args:
            rom_name: ROM name (max 21 characters)
            version: ROM version number

        Generated:
            .SNESHEADER
              ID "SNES"
              NAME "ROM NAME          "
              LOROM
              CARTRIDGETYPE $00
              ROMSIZE $08
              SRAMSIZE $00
              COUNTRY $01
              LICENSEECODE $00
              VERSION $00
            .ENDSNES

        Note: Vectors are placed separately using .ORGA directives.
        """
        self.emit_section_header("SNES ROM Header")

        # Pad or truncate ROM name to exactly 21 characters
        padded_name = rom_name[:21].ljust(21)

        self.emit_directive(".SNESHEADER")
        self.emit_directive('ID "SNES"')
        self.emit_directive(f'NAME "{padded_name}"')
        self.emit_directive("LOROM")
        self.emit_directive("CARTRIDGETYPE $00")
        self.emit_directive("ROMSIZE $08")
        self.emit_directive("SRAMSIZE $00")
        self.emit_directive("COUNTRY $01")
        self.emit_directive("LICENSEECODE $00")
        self.emit_directive(f"VERSION ${version:02X}")
        self.emit_directive(".ENDSNES")
        self.emit_blank_line()

    def emit_empty_interrupt_handler(self):
        """
        Emit empty interrupt handler for unused vectors.

        Generated:
            __empty_handler:
                RTI
        """
        self.emit_label("__empty_handler")
        self.emit_instruction("RTI")
        self.emit_blank_line()

    def emit_interrupt_vectors(self, nmi=None, irq=None, reset=None):
        """
        Emit interrupt vector table using .SNESNATIVEVECTOR and .SNESEMUVECTOR.

        Args:
            nmi: NMI handler label (or None for __empty_handler)
            irq: IRQ handler label (or None for __empty_handler)
            reset: RESET handler label (or None for __empty_handler)

        Generated:
            .SNESNATIVEVECTOR
              COP __empty_handler
              BRK __empty_handler
              ABORT __empty_handler
              NMI nmi_handler
              IRQ __empty_handler
            .ENDNATIVEVECTOR

            .SNESEMUVECTOR
              COP __empty_handler
              ABORT __empty_handler
              NMI __empty_handler
              RESET main
              IRQBRK __empty_handler
            .ENDEMUVECTOR
        """
        # Default to empty handler
        nmi = nmi or "__empty_handler"
        irq = irq or "__empty_handler"
        reset = reset or "__empty_handler"

        # Native mode vectors (5 vectors, no UNUSED)
        self.emit_section_header("Interrupt Vectors (Native Mode)")
        self.emit_directive(".SNESNATIVEVECTOR")
        self.emit_directive(f"COP {nmi}")
        self.emit_directive(f"BRK __empty_handler")
        self.emit_directive(f"ABORT __empty_handler")
        self.emit_directive(f"NMI {nmi}")
        self.emit_directive(f"IRQ {irq}")
        self.emit_directive(".ENDNATIVEVECTOR")
        self.emit_blank_line()

        # Emulation mode vectors (5 vectors, no UNUSED)
        self.emit_section_header("Interrupt Vectors (Emulation Mode)")
        self.emit_directive(".SNESEMUVECTOR")
        self.emit_directive(f"COP __empty_handler")
        self.emit_directive(f"ABORT __empty_handler")
        self.emit_directive(f"NMI __empty_handler")
        self.emit_directive(f"RESET {reset}")
        self.emit_directive(f"IRQBRK {irq}")
        self.emit_directive(".ENDEMUVECTOR")
        self.emit_blank_line()

    # ========================================================================
    # Symbol Exports
    # ========================================================================

    def emit_export(self, symbol: str):
        """
        Emit symbol export directive for .DEFINE symbols.

        Note: In WLA-DX, .EXPORT is only for .DEFINE symbols.
        Labels (function entry points) are automatically visible
        within a single-file assembly and don't need explicit exports.

        Args:
            symbol: Symbol to export

        Generated:
            .EXPORT BUFFER_SIZE
        """
        self.emit_directive(f".EXPORT {symbol}")

    def emit_exports(self, symbols: List[str]):
        """
        Emit multiple symbol exports for .DEFINE symbols.

        Note: In WLA-DX, .EXPORT is only for .DEFINE symbols.
        Labels don't need exports - they're automatically visible.

        Args:
            symbols: List of .DEFINE symbols to export

        Generated:
            ; ============================================================================
            ; Symbol Exports
            ; ============================================================================
            .EXPORT BUFFER_SIZE
            .EXPORT MAX_ENEMIES
        """
        if not symbols:
            return

        self.emit_section_header("Symbol Exports")
        for symbol in symbols:
            self.emit_export(symbol)
        self.emit_blank_line()

    # ========================================================================
    # Output Generation
    # ========================================================================

    def clear(self):
        """
        Clear all emitted content.

        Resets the emitter to its initial empty state.
        """
        self._node_emitter.nodes.clear()

    def get_nodes(self):
        """
        Get the structured AsmNode representation.

        Returns:
            List of AsmNode objects
        """
        return self._node_emitter.get_nodes()

    def set_nodes(self, nodes):
        """
        Set the nodes (after optimization passes have modified them).

        Args:
            nodes: List of AsmNode objects
        """
        self._node_emitter.nodes = nodes

    def to_string(self) -> str:
        """
        Generate complete assembly as string.

        Returns:
            Complete assembly text with newlines
        """
        from r65.compiler.codegen.asm_nodes import emit_nodes
        return emit_nodes(self.get_nodes())

    def to_lines(self) -> List[str]:
        """
        Get output as list of lines.

        Returns:
            List of assembly lines
        """
        return self.to_string().split('\n')

    def write_to_file(self, filepath: str):
        """
        Write assembly to file.

        Args:
            filepath: Output file path
        """
        with open(filepath, 'w') as f:
            f.write(self.to_string())
