"""
Assembly emitter: generates WLA-DX assembly text.

Provides methods for emitting instructions, labels, comments, and sections
in WLA-DX assembly format for the 65816 processor.
"""

from typing import List, Optional
from datetime import datetime


class AssemblyEmitter:
    """
    Emits WLA-DX assembly code.

    Manages the assembly output buffer and provides high-level methods
    for generating properly formatted assembly sections and instructions.
    """

    def __init__(self, source_file: Optional[str] = None):
        """
        Initialize assembly emitter.

        Args:
            source_file: Original R65 source file path (for header)
        """
        self.source_file = source_file or "unknown.r65"
        self.output: List[str] = []
        self.indent_level = 0
        self.current_column = 0

    # ========================================================================
    # Low-Level Emission
    # ========================================================================

    def emit_line(self, text: str = ""):
        """
        Emit a single line of text.

        Args:
            text: Line to emit (without newline)
        """
        self.output.append(text)
        self.current_column = 0

    def emit_blank_line(self):
        """Emit a blank line for spacing."""
        self.output.append("")

    def emit_comment(self, text: str):
        """
        Emit a comment line.

        Args:
            text: Comment text (without ; prefix)
        """
        self.emit_line(f"; {text}")

    # ========================================================================
    # Section Headers
    # ========================================================================

    def emit_section_header(self, title: str):
        """
        Emit a major section header with divider.

        Example:
            ; ============================================================================
            ; Direct Page Allocations
            ; ============================================================================

        Args:
            title: Section title
        """
        divider = "=" * 76
        self.emit_comment(divider)
        self.emit_comment(title)
        self.emit_comment(divider)

    def emit_subsection_header(self, title: str):
        """
        Emit a subsection header with dashes.

        Example:
            ; ----------------------------------------------------------------------------
            ; Helper Functions
            ; ----------------------------------------------------------------------------

        Args:
            title: Subsection title
        """
        divider = "-" * 76
        self.emit_comment(divider)
        self.emit_comment(title)
        self.emit_comment(divider)

    # ========================================================================
    # File Header
    # ========================================================================

    def emit_file_header(self):
        """
        Emit file header with metadata.

        Generated:
            ; ============================================================================
            ; Generated by R65 Compiler
            ; Source: main.r65
            ; Generated: 2026-01-01 14:30:00
            ; Compiler Version: 0.1.0
            ; ============================================================================
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        self.emit_section_header("Generated by R65 Compiler")
        self.emit_comment(f"Source: {self.source_file}")
        self.emit_comment(f"Generated: {now}")
        self.emit_comment("Compiler Version: 0.1.0")
        self.emit_comment("=" * 76)
        self.emit_blank_line()

    # ========================================================================
    # Processor Directives
    # ========================================================================

    def emit_processor_directive(self):
        """
        Emit processor directive for 65816.

        Generated:
            .65816
        """
        self.emit_line(".65816")
        self.emit_blank_line()

    # ========================================================================
    # Memory Map
    # ========================================================================

    def emit_memory_map(self, rom_type: str = "lorom", banks: int = 1):
        """
        Emit WLA-DX memory map and ROM bank map.

        Args:
            rom_type: "lorom" (32KB banks) or "hirom" (64KB banks)
            banks: Number of ROM banks

        Generated (LoROM):
            .MEMORYMAP
                DEFAULTSLOT 0
                SLOTSIZE $8000
                SLOT 0 $8000
            .ENDME

            .ROMBANKMAP
                BANKSTOTAL 1
                BANKSIZE $8000
                BANKS 1
            .ENDRO
        """
        self.emit_section_header(f"Memory Map ({rom_type.upper()})")

        if rom_type.lower() == "lorom":
            slot_size = 0x8000  # 32KB
            slot_addr = 0x8000
        else:  # hirom
            slot_size = 0x10000  # 64KB
            slot_addr = 0x0000

        # Memory map
        self.emit_line(".MEMORYMAP")
        self.emit_line("    DEFAULTSLOT 0")
        self.emit_line(f"    SLOTSIZE ${slot_size:04X}")
        self.emit_line(f"    SLOT 0 ${slot_addr:04X}")
        self.emit_line(".ENDME")
        self.emit_blank_line()

        # ROM bank map
        self.emit_line(".ROMBANKMAP")
        self.emit_line(f"    BANKSTOTAL {banks}")
        self.emit_line(f"    BANKSIZE ${slot_size:04X}")
        self.emit_line(f"    BANKS {banks}")
        self.emit_line(".ENDRO")
        self.emit_blank_line()

    # ========================================================================
    # Bank Directives
    # ========================================================================

    def emit_bank_directive(self, bank_num: int, slot: int = 0):
        """
        Emit bank directive and origin.

        Args:
            bank_num: Bank number
            slot: Slot number (usually 0)

        Generated:
            .BANK 0 SLOT 0
            .ORG 0
        """
        self.emit_line(f".BANK {bank_num} SLOT {slot}")
        self.emit_line(".ORG 0")
        self.emit_blank_line()

    # ========================================================================
    # Labels
    # ========================================================================

    def emit_label(self, label: str):
        """
        Emit a label.

        Args:
            label: Label name (with or without trailing :)

        Generated:
            label:
        """
        if not label.endswith(':'):
            label += ':'
        self.emit_line(label)

    def emit_local_label(self, label: str):
        """
        Emit a local label with indentation.

        Args:
            label: Label name

        Generated:
            __L1:
        """
        self.emit_label(label)

    # ========================================================================
    # Instructions
    # ========================================================================

    def emit_instruction(self, mnemonic: str, operand: Optional[str] = None,
                        comment: Optional[str] = None):
        """
        Emit a single instruction.

        Args:
            mnemonic: Instruction mnemonic (e.g., "LDA", "STA")
            operand: Operand (e.g., "#$42", "$20")
            comment: Optional inline comment

        Generated:
            LDA #$42                ; Load immediate
            STA $20                 ; Store to zero-page
            RTS
        """
        # Build instruction
        if operand:
            instr = f"    {mnemonic} {operand}"
        else:
            instr = f"    {mnemonic}"

        # Add comment if provided
        if comment:
            # Pad to column 32 for alignment
            padding = max(1, 32 - len(instr))
            instr += " " * padding + f"; {comment}"

        self.emit_line(instr)

    # ========================================================================
    # Symbol Definitions
    # ========================================================================

    def emit_define(self, name: str, value: int, comment: Optional[str] = None):
        """
        Emit a .DEFINE directive.

        Args:
            name: Symbol name
            value: Address value
            comment: Optional inline comment

        Generated:
            .DEFINE TEMP $20        ; main.r65:5
        """
        line = f".DEFINE {name} ${value:04X}"

        if comment:
            padding = max(1, 32 - len(line))
            line += " " * padding + f"; {comment}"

        self.emit_line(line)

    def emit_equ(self, name: str, value: int, comment: Optional[str] = None):
        """
        Emit a .EQU directive for constants.

        Args:
            name: Constant name
            value: Constant value
            comment: Optional inline comment

        Generated:
            .EQU SCREEN_WIDTH 256   ; Constant
        """
        line = f".EQU {name} {value}"

        if comment:
            padding = max(1, 32 - len(line))
            line += " " * padding + f"; {comment}"

        self.emit_line(line)

    # ========================================================================
    # Data Directives
    # ========================================================================

    def emit_byte(self, values: List[int]):
        """
        Emit byte data (.DB directive).

        Args:
            values: List of byte values

        Generated:
            .DB $80, $83, $86, $89
        """
        # Format as hex bytes
        hex_values = [f"${v:02X}" for v in values]

        # Emit 8 values per line for readability
        for i in range(0, len(hex_values), 8):
            chunk = hex_values[i:i+8]
            self.emit_line(f"    .DB {', '.join(chunk)}")

    def emit_word(self, values: List[int]):
        """
        Emit word data (.DW directive).

        Args:
            values: List of word values

        Generated:
            .DW $1234, $5678
        """
        hex_values = [f"${v:04X}" for v in values]

        # Emit 8 values per line
        for i in range(0, len(hex_values), 8):
            chunk = hex_values[i:i+8]
            self.emit_line(f"    .DW {', '.join(chunk)}")

    def emit_space(self, size: int, fill_value: int = 0):
        """
        Emit space reservation (.DSB directive).

        Args:
            size: Number of bytes to reserve
            fill_value: Fill value (default 0)

        Generated:
            .DSB 256, 0
        """
        self.emit_line(f"    .DSB {size}, {fill_value}")

    # ========================================================================
    # Interrupt Vectors
    # ========================================================================

    def emit_interrupt_vectors(self, nmi=None, irq=None, reset=None):
        """
        Emit interrupt vector table.

        Args:
            nmi: NMI handler label (or None for 0)
            irq: IRQ handler label (or None for 0)
            reset: RESET handler label (or None for 0)

        Generated:
            ; ============================================================================
            ; Interrupt Vectors (Native Mode)
            ; ============================================================================
            .ORGA $FFE4
            .dw 0                       ; COP
            .dw 0                       ; BRK
            .dw 0                       ; ABORT
            .dw nmi_handler             ; NMI
            .dw 0                       ; (unused)
            .dw 0                       ; IRQ
        """
        self.emit_section_header("Interrupt Vectors (Native Mode)")
        self.emit_line(".ORGA $FFE4")
        self.emit_instruction(".dw", "0", "COP")
        self.emit_instruction(".dw", "0", "BRK")
        self.emit_instruction(".dw", "0", "ABORT")
        self.emit_instruction(".dw", nmi or "0", "NMI")
        self.emit_instruction(".dw", "0", "(unused)")
        self.emit_instruction(".dw", irq or "0", "IRQ")
        self.emit_blank_line()

        self.emit_section_header("Interrupt Vectors (Emulation Mode)")
        self.emit_line(".ORGA $FFF4")
        self.emit_instruction(".dw", "0", "COP")
        self.emit_instruction(".dw", "0", "(unused)")
        self.emit_instruction(".dw", "0", "ABORT")
        self.emit_instruction(".dw", "0", "NMI")
        self.emit_instruction(".dw", reset or "0", "RESET")
        self.emit_instruction(".dw", "0", "IRQ/BRK")
        self.emit_blank_line()

    # ========================================================================
    # Symbol Exports
    # ========================================================================

    def emit_export(self, symbol: str):
        """
        Emit symbol export directive.

        Args:
            symbol: Symbol to export

        Generated:
            .EXPORT main
        """
        self.emit_line(f".EXPORT {symbol}")

    def emit_exports(self, symbols: List[str]):
        """
        Emit multiple symbol exports.

        Args:
            symbols: List of symbols to export

        Generated:
            ; ============================================================================
            ; Symbol Exports
            ; ============================================================================
            .EXPORT main
            .EXPORT function1
            .EXPORT function2
        """
        if not symbols:
            return

        self.emit_section_header("Symbol Exports")
        for symbol in symbols:
            self.emit_export(symbol)
        self.emit_blank_line()

    # ========================================================================
    # Output Generation
    # ========================================================================

    def to_string(self) -> str:
        """
        Generate complete assembly as string.

        Returns:
            Complete assembly text with newlines
        """
        return '\n'.join(self.output)

    def to_lines(self) -> List[str]:
        """
        Get output as list of lines.

        Returns:
            List of assembly lines
        """
        return self.output.copy()

    def write_to_file(self, filepath: str):
        """
        Write assembly to file.

        Args:
            filepath: Output file path
        """
        with open(filepath, 'w') as f:
            f.write(self.to_string())
