; ============================================================================
; Generated by R65 Compiler
; ============================================================================
; Source: <unknown>
; Generated: 2026-01-03 09:04:11
; Compiler Version: 0.1.0
; ============================================================================

.65816

; ============================================================================
; Memory Map (LOROM)
; ============================================================================
.MEMORYMAP
    DEFAULTSLOT 0
    SLOTSIZE $8000
    SLOT 0 $8000
.ENDME

.ROMBANKMAP
    BANKSTOTAL 1
    BANKSIZE $8000
    BANKS 1
.ENDRO

; ----------------------------------------------------------------------------
; set_flag
;
; Parameters:
;   a: u8
;
; Returns: u8
;
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
set_flag:
    LDA $16
    CLC
    ADC #$01
    STA $17
    LDA #$03
    LDA $17
    RTS

; ----------------------------------------------------------------------------
; main
;
; Returns: !
;
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; Entry: true
; ----------------------------------------------------------------------------
main:
    LDA #$05
    PHA  ; Push stack arg 0
    JSR set_flag
    PLA  ; Clean up stack arg
    STA $16
    JMP __L1
__L1:
    LDA #1
    BEQ __L3  ; Branch if zero
    JMP __L2
__L2:
    JMP __L1
__L3:

; ============================================================================
; Interrupt Vectors (Native Mode)
; ============================================================================
.ORGA $FFE4
.dw 0                       ; COP
.dw 0                       ; BRK
.dw 0                       ; ABORT
.dw 0                       ; NMI
.dw 0                       ; (unused)
.dw 0                       ; IRQ

; ============================================================================
; Interrupt Vectors (Emulation Mode)
; ============================================================================
.ORGA $FFF4
.dw 0                       ; COP
.dw 0                       ; (unused)
.dw 0                       ; ABORT
.dw 0                       ; NMI
.dw main                    ; RESET
.dw 0                       ; IRQ/BRK

; ============================================================================
; Symbol Exports
; ============================================================================
.EXPORT set_flag
.EXPORT main
