; ============================================================================
; Generated by R65 Compiler
; ============================================================================
; Source: <unknown>
; Generated: 2026-01-03 01:44:44
; Compiler Version: 0.1.0
; ============================================================================

.65816

; ============================================================================
; Memory Map (LOROM)
; ============================================================================
.MEMORYMAP
    DEFAULTSLOT 0
    SLOTSIZE $8000
    SLOT 0 $8000
.ENDME

.ROMBANKMAP
    BANKSTOTAL 1
    BANKSIZE $8000
    BANKS 1
.ENDRO

; ============================================================================
; Direct Page Allocations
; ============================================================================
.DEFINE FLAGS $0010             ; Auto-allocated

; ----------------------------------------------------------------------------
; __init_start
; 
; ----------------------------------------------------------------------------
__init_start:
    LDA #$81
    STA $10
    RTS

; ----------------------------------------------------------------------------
; test_rotate_left
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_rotate_left:
    LDA $10
    STA $16
    LDA $16
    ROL
    STA $17
    LDA $17
    RTS

; ----------------------------------------------------------------------------
; test_rotate_right
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_rotate_right:
    LDA $10
    STA $16
    LDA $16
    ROR
    STA $17
    LDA $17
    RTS

; ----------------------------------------------------------------------------
; test_rotate_left_multiple
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_rotate_left_multiple:
    LDA $10
    STA $16
    LDA $16
    ROL
    ROL
    ROL
    STA $17
    LDA $17
    RTS

; ----------------------------------------------------------------------------
; test_rotate_right_multiple
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_rotate_right_multiple:
    LDA $10
    STA $16
    LDA $16
    ROR
    ROR
    ROR
    ROR
    STA $17
    LDA $17
    RTS

; ----------------------------------------------------------------------------
; test_rotate_expression
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_rotate_expression:
    LDA #$FF
    STA $16
    LDA $16
    ROL
    ROL
    STA $17
    LDA $17
    RTS

; ----------------------------------------------------------------------------
; main
; 
; Returns: !
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; Entry: true
; ----------------------------------------------------------------------------
main:
    JSR __init_start
    JSR test_rotate_left
    STA $16
    LDA $16
    JSR test_rotate_right
    STA $17
    LDA $17
    JSR test_rotate_left_multiple
    STA $18
    LDA $18
    JMP __L1
__L1:
    LDA #1
    BEQ __L3                    ; Branch if zero
    JMP __L2
__L2:
    JMP __L1
__L3:

; ============================================================================
; Interrupt Vectors (Native Mode)
; ============================================================================
.ORGA $FFE4
    .dw 0                       ; COP
    .dw 0                       ; BRK
    .dw 0                       ; ABORT
    .dw 0                       ; NMI
    .dw 0                       ; (unused)
    .dw 0                       ; IRQ

; ============================================================================
; Interrupt Vectors (Emulation Mode)
; ============================================================================
.ORGA $FFF4
    .dw 0                       ; COP
    .dw 0                       ; (unused)
    .dw 0                       ; ABORT
    .dw 0                       ; NMI
    .dw main                    ; RESET
    .dw 0                       ; IRQ/BRK

; ============================================================================
; Symbol Exports
; ============================================================================
.EXPORT __init_start
.EXPORT test_rotate_left
.EXPORT test_rotate_right
.EXPORT test_rotate_left_multiple
.EXPORT test_rotate_right_multiple
.EXPORT test_rotate_expression
.EXPORT main
