; ============================================================================
; Generated by R65 Compiler
; ============================================================================
; Source: <unknown>
; Generated: 2026-01-03 00:35:08
; Compiler Version: 0.1.0
; ============================================================================

.65816

; ============================================================================
; Memory Map (LOROM)
; ============================================================================
.MEMORYMAP
    DEFAULTSLOT 0
    SLOTSIZE $8000
    SLOT 0 $8000
.ENDME

.ROMBANKMAP
    BANKSTOTAL 1
    BANKSIZE $8000
    BANKS 1
.ENDRO

; ============================================================================
; Direct Page Allocations
; ============================================================================
.DEFINE MATH_FUNC $0040         ; Explicit

; ----------------------------------------------------------------------------
; add_ten
; 
; Parameters:
;   value: u8
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
add_ten:
    CLC
    ADC #$0A
    RTS

; ----------------------------------------------------------------------------
; add_twenty
; 
; Parameters:
;   value: u8
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
add_twenty:
    CLC
    ADC #$14
    RTS

; ----------------------------------------------------------------------------
; test_assign_function_pointer
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_assign_function_pointer:
    LDA #<add_ten               ; Load function address low byte
    STA $16
    LDA #>add_ten               ; Load function address high byte
    STA $17
    LDA $16
    STA $40
    RTS

; ----------------------------------------------------------------------------
; test_call_through_pointer
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_call_through_pointer:
    LDA $40
    STA $16
    LDA #$05
    PHA                         ; Push stack arg 0
    LDA $17                     ; Load high byte
    PHA                         ; Push high
    LDA $16                     ; Load low byte
    PHA                         ; Push low
    RTS                         ; Indirect near call via trampoline
    PLA                         ; Clean up stack arg
    STA $17
    LDA $17
    RTS

; ----------------------------------------------------------------------------
; test_change_pointer
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_change_pointer:
    LDA #<add_twenty            ; Load function address low byte
    STA $16
    LDA #>add_twenty            ; Load function address high byte
    STA $17
    LDA $16
    STA $40
    LDA $40
    STA $17
    LDA #$05
    PHA                         ; Push stack arg 0
    LDA $18                     ; Load high byte
    PHA                         ; Push high
    LDA $17                     ; Load low byte
    PHA                         ; Push low
    RTS                         ; Indirect near call via trampoline
    PLA                         ; Clean up stack arg
    STA $18
    LDA $18
    RTS

; ----------------------------------------------------------------------------
; test_local_function_pointer
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_local_function_pointer:
    LDA #<add_ten               ; Load function address low byte
    STA $16
    LDA #>add_ten               ; Load function address high byte
    STA $17
    LDA #$03
    PHA                         ; Push stack arg 0
    LDA $17                     ; Load high byte
    PHA                         ; Push high
    LDA $16                     ; Load low byte
    PHA                         ; Push low
    RTS                         ; Indirect near call via trampoline
    PLA                         ; Clean up stack arg
    STA $17
    LDA $17
    LDA #<add_twenty            ; Load function address low byte
    STA $18
    LDA #>add_twenty            ; Load function address high byte
    STA $19
    LDA $18
    STA $16
    LDA #$03
    PHA                         ; Push stack arg 0
    LDA $17                     ; Load high byte
    PHA                         ; Push high
    LDA $16                     ; Load low byte
    PHA                         ; Push low
    RTS                         ; Indirect near call via trampoline
    PLA                         ; Clean up stack arg
    STA $1A
    LDA $1A
    RTS

; ----------------------------------------------------------------------------
; main
; 
; Returns: !
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; Entry: true
; ----------------------------------------------------------------------------
main:
    JSR test_assign_function_pointer
    JSR test_call_through_pointer
    JSR test_change_pointer
    JSR test_local_function_pointer
    JMP __L1
__L1:
    LDA #1
    BEQ __L3                    ; Branch if zero
    JMP __L2
__L2:
    JMP __L1
__L3:

; ============================================================================
; Interrupt Vectors (Native Mode)
; ============================================================================
.ORGA $FFE4
    .dw 0                       ; COP
    .dw 0                       ; BRK
    .dw 0                       ; ABORT
    .dw 0                       ; NMI
    .dw 0                       ; (unused)
    .dw 0                       ; IRQ

; ============================================================================
; Interrupt Vectors (Emulation Mode)
; ============================================================================
.ORGA $FFF4
    .dw 0                       ; COP
    .dw 0                       ; (unused)
    .dw 0                       ; ABORT
    .dw 0                       ; NMI
    .dw main                    ; RESET
    .dw 0                       ; IRQ/BRK

; ============================================================================
; Symbol Exports
; ============================================================================
.EXPORT add_ten
.EXPORT add_twenty
.EXPORT test_assign_function_pointer
.EXPORT test_call_through_pointer
.EXPORT test_change_pointer
.EXPORT test_local_function_pointer
.EXPORT main
