; ============================================================================
; Generated by R65 Compiler
; ============================================================================
; Source: <unknown>
; Generated: 2026-01-03 00:37:23
; Compiler Version: 0.1.0
; ============================================================================

.65816

; ============================================================================
; Memory Map (LOROM)
; ============================================================================
.MEMORYMAP
    DEFAULTSLOT 0
    SLOTSIZE $8000
    SLOT 0 $8000
.ENDME

.ROMBANKMAP
    BANKSTOTAL 1
    BANKSIZE $8000
    BANKS 1
.ENDRO

; ============================================================================
; RAM Allocations
; ============================================================================
.DEFINE HANDLERS $7E0000        ; Auto-allocated - 3 bytes

; ----------------------------------------------------------------------------
; add_ten
; 
; Parameters:
;   value: u8
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
add_ten:
    CLC
    ADC #$0A
    RTS

; ----------------------------------------------------------------------------
; add_twenty
; 
; Parameters:
;   value: u8
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
add_twenty:
    CLC
    ADC #$14
    RTS

; ----------------------------------------------------------------------------
; add_thirty
; 
; Parameters:
;   value: u8
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
add_thirty:
    CLC
    ADC #$1E
    RTS

; ----------------------------------------------------------------------------
; test_array_of_function_pointers
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_array_of_function_pointers:
    LDA #<add_ten               ; Load function address low byte
    STA $16
    LDA #>add_ten               ; Load function address high byte
    STA $17
    LDA $16
    STA $00
    LDA #<add_twenty            ; Load function address low byte
    STA $17
    LDA #>add_twenty            ; Load function address high byte
    STA $18
    LDA $17
    STA $02
    LDA #<add_thirty            ; Load function address low byte
    STA $18
    LDA #>add_thirty            ; Load function address high byte
    STA $19
    LDA $18
    STA $04
    LDA $02
    STA $1A
    LDA #$05
    PHA                         ; Push stack arg 0
    LDA $1B                     ; Load high byte
    PHA                         ; Push high
    LDA $1A                     ; Load low byte
    PHA                         ; Push low
    RTS                         ; Indirect near call via trampoline
    PLA                         ; Clean up stack arg
    STA $00,S
    LDA $00,S
    RTS

; ----------------------------------------------------------------------------
; main
; 
; Returns: !
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; Entry: true
; ----------------------------------------------------------------------------
main:
    JSR test_array_of_function_pointers
    JMP __L1
__L1:
    LDA #1
    BEQ __L3                    ; Branch if zero
    JMP __L2
__L2:
    JMP __L1
__L3:

; ============================================================================
; Interrupt Vectors (Native Mode)
; ============================================================================
.ORGA $FFE4
    .dw 0                       ; COP
    .dw 0                       ; BRK
    .dw 0                       ; ABORT
    .dw 0                       ; NMI
    .dw 0                       ; (unused)
    .dw 0                       ; IRQ

; ============================================================================
; Interrupt Vectors (Emulation Mode)
; ============================================================================
.ORGA $FFF4
    .dw 0                       ; COP
    .dw 0                       ; (unused)
    .dw 0                       ; ABORT
    .dw 0                       ; NMI
    .dw main                    ; RESET
    .dw 0                       ; IRQ/BRK

; ============================================================================
; Symbol Exports
; ============================================================================
.EXPORT add_ten
.EXPORT add_twenty
.EXPORT add_thirty
.EXPORT test_array_of_function_pointers
.EXPORT main
