; ============================================================================
; Generated by R65 Compiler
; ============================================================================
; Source: <unknown>
; Generated: 2026-01-03 00:24:15
; Compiler Version: 0.1.0
; ============================================================================

.65816

; ============================================================================
; Memory Map (LOROM)
; ============================================================================
.MEMORYMAP
    DEFAULTSLOT 0
    SLOTSIZE $8000
    SLOT 0 $8000
.ENDME

.ROMBANKMAP
    BANKSTOTAL 1
    BANKSIZE $8000
    BANKS 1
.ENDRO

; ============================================================================
; Direct Page Allocations
; ============================================================================
.DEFINE VALUE $0020             ; Explicit
.DEFINE PTR $0022               ; Explicit - 2 bytes

; ----------------------------------------------------------------------------
; __init_start
; 
; ----------------------------------------------------------------------------
__init_start:
    LDA #$42
    STA $20
    RTS

; ----------------------------------------------------------------------------
; test_addressof
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_addressof:
    LDA #<$0020                 ; Load address of VALUE
    STA $16
    LDA $16
    STA $22
    RTS

; ----------------------------------------------------------------------------
; test_dereference_load
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_dereference_load:
    LDA $22
    STA $16
    LDA ($16)                   ; Load through pointer
    STA $17
    LDA $17
    RTS

; ----------------------------------------------------------------------------
; test_dereference_store
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
test_dereference_store:
    LDA $22
    STA $16
    LDA #$99
    STA ($16)                   ; Store through pointer
    RTS

; ----------------------------------------------------------------------------
; main
; 
; Returns: !
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; Entry: true
; ----------------------------------------------------------------------------
main:
    JSR __init_start
    JSR test_addressof
    JSR test_dereference_load
    JSR test_dereference_store
    JMP __L1
__L1:
    LDA #1
    BEQ __L3                    ; Branch if zero
    JMP __L2
__L2:
    JMP __L1
__L3:

; ============================================================================
; Interrupt Vectors (Native Mode)
; ============================================================================
.ORGA $FFE4
    .dw 0                       ; COP
    .dw 0                       ; BRK
    .dw 0                       ; ABORT
    .dw 0                       ; NMI
    .dw 0                       ; (unused)
    .dw 0                       ; IRQ

; ============================================================================
; Interrupt Vectors (Emulation Mode)
; ============================================================================
.ORGA $FFF4
    .dw 0                       ; COP
    .dw 0                       ; (unused)
    .dw 0                       ; ABORT
    .dw 0                       ; NMI
    .dw main                    ; RESET
    .dw 0                       ; IRQ/BRK

; ============================================================================
; Symbol Exports
; ============================================================================
.EXPORT __init_start
.EXPORT test_addressof
.EXPORT test_dereference_load
.EXPORT test_dereference_store
.EXPORT main
