; ============================================================================
; Generated by R65 Compiler
; ============================================================================
; Source: <unknown>
; Generated: 2026-01-08 17:06:21
; Compiler Version: 0.1.0
; ============================================================================

.65816

; ============================================================================
; Memory Map (LOROM)
; ============================================================================
.MEMORYMAP
    DEFAULTSLOT 0
    SLOTSIZE $8000
    SLOT 0 $8000
.ENDME

.ROMBANKMAP
    BANKSTOTAL 1
    BANKSIZE $8000
    BANKS 1
.ENDRO

; ============================================================================
; Constants
; ============================================================================
.EQU SCREEN_WIDTH 256
.EQU SCREEN_HEIGHT_NORMAL 224
.EQU SCREEN_HEIGHT_OVERSCAN 239
.EQU TILES_PER_ROW 32
.EQU TILES_PER_COL_NORMAL 28
.EQU TILES_PER_COL_OVERSCAN 30
.EQU TILE_SIZE_8 8
.EQU TILE_SIZE_16 16
.EQU TILE_BYTES_2BPP 16
.EQU TILE_BYTES_4BPP 32
.EQU TILE_BYTES_8BPP 64
.EQU BRIGHTNESS_OFF 0
.EQU BRIGHTNESS_FULL 15
.EQU FORCE_BLANK 128
.EQU SCREEN_ON_FULL 15
.EQU BGMODE_0 0
.EQU BGMODE_1 1
.EQU BGMODE_2 2
.EQU BGMODE_3 3
.EQU BGMODE_4 4
.EQU BGMODE_5 5
.EQU BGMODE_6 6
.EQU BGMODE_7 7
.EQU BG1_TILE_16X16 16
.EQU BG2_TILE_16X16 32
.EQU BG3_TILE_16X16 64
.EQU BG4_TILE_16X16 128
.EQU OBJSEL_8X8_16X16 0
.EQU OBJSEL_8X8_32X32 32
.EQU OBJSEL_8X8_64X64 64
.EQU OBJSEL_16X16_32X32 96
.EQU OBJSEL_16X16_64X64 128
.EQU OBJSEL_32X32_64X64 160
.EQU OBJSEL_16X32_32X64 192
.EQU OBJSEL_16X32_32X32 224
.EQU VMAIN_INCREMENT_LOW 0
.EQU VMAIN_INCREMENT_HIGH 128
.EQU VMAIN_INCREMENT_1 0
.EQU VMAIN_INCREMENT_32 1
.EQU VMAIN_INCREMENT_128 2
.EQU DMA_MODE_1REG_1WRITE 0
.EQU DMA_MODE_2REG_1WRITE 1
.EQU DMA_MODE_1REG_2WRITE 2
.EQU DMA_MODE_2REG_2WRITE 3
.EQU DMA_MODE_4REG_1WRITE 4
.EQU DMA_DIRECTION_TO_PPU 0
.EQU DMA_DIRECTION_TO_CPU 128
.EQU DMA_INCREMENT 0
.EQU DMA_DECREMENT 16
.EQU DMA_FIXED 8
.EQU NMI_ENABLE 128
.EQU IRQ_ENABLE_V 32
.EQU IRQ_ENABLE_HV 48
.EQU AUTOJOY_ENABLE 1
.EQU SCREEN_BG1 1
.EQU SCREEN_BG2 2
.EQU SCREEN_BG3 4
.EQU SCREEN_BG4 8
.EQU SCREEN_OBJ 16
.EQU JOY_B 32768
.EQU JOY_Y 16384
.EQU JOY_SELECT 8192
.EQU JOY_START 4096
.EQU JOY_UP 2048
.EQU JOY_DOWN 1024
.EQU JOY_LEFT 512
.EQU JOY_RIGHT 256
.EQU JOY_A 128
.EQU JOY_X 64
.EQU JOY_L 32
.EQU JOY_R 16
.EQU JOYH_B 128
.EQU JOYH_Y 64
.EQU JOYH_SELECT 32
.EQU JOYH_START 16
.EQU JOYH_UP 8
.EQU JOYH_DOWN 4
.EQU JOYH_LEFT 2
.EQU JOYH_RIGHT 1
.EQU JOYL_A 128
.EQU JOYL_X 64
.EQU JOYL_L 32
.EQU JOYL_R 16
.EQU CGADSUB_ADD 0
.EQU CGADSUB_SUB 128
.EQU CGADSUB_HALF 64
.EQU CGADSUB_BG1 1
.EQU CGADSUB_BG2 2
.EQU CGADSUB_BG3 4
.EQU CGADSUB_BG4 8
.EQU CGADSUB_OBJ 16
.EQU CGADSUB_BACKDROP 32
.EQU COLDATA_RED 32
.EQU COLDATA_GREEN 64
.EQU COLDATA_BLUE 128
.EQU VRAM_BG1_TILES 0
.EQU VRAM_BG2_TILES 16384
.EQU VRAM_BG1_MAP 28672
.EQU VRAM_BG2_MAP 29696
.EQU VRAM_OBJ_TILES 24576
.EQU OAM_X 0
.EQU OAM_Y 1
.EQU OAM_TILE 2
.EQU OAM_ATTR 3
.EQU OAM_FLIP_V 128
.EQU OAM_FLIP_H 64
.EQU OAM_PRIORITY_0 0
.EQU OAM_PRIORITY_1 16
.EQU OAM_PRIORITY_2 32
.EQU OAM_PRIORITY_3 48
.EQU OAM_PALETTE_0 0
.EQU OAM_PALETTE_1 2
.EQU OAM_PALETTE_2 4
.EQU OAM_PALETTE_3 6
.EQU OAM_PALETTE_4 8
.EQU OAM_PALETTE_5 10
.EQU OAM_PALETTE_6 12
.EQU OAM_PALETTE_7 14
.EQU OAM_NAME_TABLE 1
.EQU SPC_READY 170
.EQU SPC_BEGIN 204
.EQU R_MASK 31
.EQU G_MASK 992
.EQU B_MASK 31744
.EQU SPR_HFLIP 16384
.EQU SPR_VFLIP 32768
.EQU SPR_PRIORITY_0 0
.EQU SPR_PRIORITY_1 4096
.EQU SPR_PRIORITY_2 8192
.EQU SPR_PRIORITY_3 12288
.EQU SPR_PALETTE_0 0
.EQU SPR_PALETTE_1 512
.EQU SPR_PALETTE_2 1024
.EQU SPR_PALETTE_3 1536
.EQU SPR_PALETTE_4 2048
.EQU SPR_PALETTE_5 2560
.EQU SPR_PALETTE_6 3072
.EQU SPR_PALETTE_7 3584
.EQU BG_HFLIP 16384
.EQU BG_VFLIP 32768
.EQU BG_PRIORITY 8192
.EQU BG_PALETTE_0 0
.EQU BG_PALETTE_1 1024
.EQU BG_PALETTE_2 2048
.EQU BG_PALETTE_3 3072
.EQU BG_PALETTE_4 4096
.EQU BG_PALETTE_5 5120
.EQU BG_PALETTE_6 6144
.EQU BG_PALETTE_7 7168
.EQU FALSE 0
.EQU TRUE 1

; ============================================================================
; Hardware Register Definitions
; ============================================================================
.DEFINE INIDISP $2100           ; Hardware register
.DEFINE OBSEL $2101             ; Hardware register
.DEFINE OAMADDL $2102           ; Hardware register
.DEFINE OAMADDH $2103           ; Hardware register
.DEFINE OAMDATA $2104           ; Hardware register
.DEFINE BGMODE $2105            ; Hardware register
.DEFINE MOSAIC $2106            ; Hardware register
.DEFINE BG1SC $2107             ; Hardware register
.DEFINE BG2SC $2108             ; Hardware register
.DEFINE BG3SC $2109             ; Hardware register
.DEFINE BG4SC $210A             ; Hardware register
.DEFINE BG12NBA $210B           ; Hardware register
.DEFINE BG34NBA $210C           ; Hardware register
.DEFINE BG1HOFS $210D           ; Hardware register
.DEFINE BG1VOFS $210E           ; Hardware register
.DEFINE BG2HOFS $210F           ; Hardware register
.DEFINE BG2VOFS $2110           ; Hardware register
.DEFINE BG3HOFS $2111           ; Hardware register
.DEFINE BG3VOFS $2112           ; Hardware register
.DEFINE BG4HOFS $2113           ; Hardware register
.DEFINE BG4VOFS $2114           ; Hardware register
.DEFINE VMAIN $2115             ; Hardware register
.DEFINE VMADDL $2116            ; Hardware register
.DEFINE VMADDH $2117            ; Hardware register
.DEFINE VMDATAL $2118           ; Hardware register
.DEFINE VMDATAH $2119           ; Hardware register
.DEFINE M7SEL $211A             ; Hardware register
.DEFINE M7A $211B               ; Hardware register
.DEFINE M7B $211C               ; Hardware register
.DEFINE M7C $211D               ; Hardware register
.DEFINE M7D $211E               ; Hardware register
.DEFINE M7X $211F               ; Hardware register
.DEFINE M7Y $2120               ; Hardware register
.DEFINE CGADD $2121             ; Hardware register
.DEFINE CGDATA $2122            ; Hardware register
.DEFINE W12SEL $2123            ; Hardware register
.DEFINE W34SEL $2124            ; Hardware register
.DEFINE WOBJSEL $2125           ; Hardware register
.DEFINE WH0 $2126               ; Hardware register
.DEFINE WH1 $2127               ; Hardware register
.DEFINE WH2 $2128               ; Hardware register
.DEFINE WH3 $2129               ; Hardware register
.DEFINE WBGLOG $212A            ; Hardware register
.DEFINE WOBJLOG $212B           ; Hardware register
.DEFINE TM $212C                ; Hardware register
.DEFINE TS $212D                ; Hardware register
.DEFINE TMW $212E               ; Hardware register
.DEFINE TSW $212F               ; Hardware register
.DEFINE CGWSEL $2130            ; Hardware register
.DEFINE CGADSUB $2131           ; Hardware register
.DEFINE COLDATA $2132           ; Hardware register
.DEFINE SETINI $2133            ; Hardware register
.DEFINE MPYL $2134              ; Hardware register
.DEFINE MPYM $2135              ; Hardware register
.DEFINE MPYH $2136              ; Hardware register
.DEFINE SLHV $2137              ; Hardware register
.DEFINE OAMDATAREAD $2138       ; Hardware register
.DEFINE VMDATALREAD $2139       ; Hardware register
.DEFINE VMDATAHREAD $213A       ; Hardware register
.DEFINE CGDATAREAD $213B        ; Hardware register
.DEFINE OPHCT $213C             ; Hardware register
.DEFINE OPVCT $213D             ; Hardware register
.DEFINE STAT77 $213E            ; Hardware register
.DEFINE STAT78 $213F            ; Hardware register
.DEFINE APUIO0 $2140            ; Hardware register
.DEFINE APUIO1 $2141            ; Hardware register
.DEFINE APUIO2 $2142            ; Hardware register
.DEFINE APUIO3 $2143            ; Hardware register
.DEFINE WMDATA $2180            ; Hardware register
.DEFINE WMADDL $2181            ; Hardware register
.DEFINE WMADDM $2182            ; Hardware register
.DEFINE WMADDH $2183            ; Hardware register
.DEFINE NMITIMEN $4200          ; Hardware register
.DEFINE WRIO $4201              ; Hardware register
.DEFINE WRMPYA $4202            ; Hardware register
.DEFINE WRMPYB $4203            ; Hardware register
.DEFINE WRDIVL $4204            ; Hardware register
.DEFINE WRDIVH $4205            ; Hardware register
.DEFINE WRDIVB $4206            ; Hardware register
.DEFINE HTIMEL $4207            ; Hardware register
.DEFINE HTIMEH $4208            ; Hardware register
.DEFINE VTIMEL $4209            ; Hardware register
.DEFINE VTIMEH $420A            ; Hardware register
.DEFINE MDMAEN $420B            ; Hardware register
.DEFINE HDMAEN $420C            ; Hardware register
.DEFINE MEMSEL $420D            ; Hardware register
.DEFINE RDNMI $4210             ; Hardware register
.DEFINE TIMEUP $4211            ; Hardware register
.DEFINE HVBJOY $4212            ; Hardware register
.DEFINE RDIO $4213              ; Hardware register
.DEFINE RDDIVL $4214            ; Hardware register
.DEFINE RDDIVH $4215            ; Hardware register
.DEFINE RDMPYL $4216            ; Hardware register
.DEFINE RDMPYH $4217            ; Hardware register
.DEFINE JOY1L $4218             ; Hardware register
.DEFINE JOY1H $4219             ; Hardware register
.DEFINE JOY2L $421A             ; Hardware register
.DEFINE JOY2H $421B             ; Hardware register
.DEFINE JOY3L $421C             ; Hardware register
.DEFINE JOY3H $421D             ; Hardware register
.DEFINE JOY4L $421E             ; Hardware register
.DEFINE JOY4H $421F             ; Hardware register
.DEFINE DMAP0 $4300             ; Hardware register
.DEFINE BBAD0 $4301             ; Hardware register
.DEFINE A1T0L $4302             ; Hardware register
.DEFINE A1T0H $4303             ; Hardware register
.DEFINE A1B0 $4304              ; Hardware register
.DEFINE DAS0L $4305             ; Hardware register
.DEFINE DAS0H $4306             ; Hardware register
.DEFINE DASB0 $4307             ; Hardware register
.DEFINE A2A0L $4308             ; Hardware register
.DEFINE A2A0H $4309             ; Hardware register
.DEFINE NTRL0 $430A             ; Hardware register
.DEFINE DMAP1 $4310             ; Hardware register
.DEFINE BBAD1 $4311             ; Hardware register
.DEFINE A1T1L $4312             ; Hardware register
.DEFINE A1T1H $4313             ; Hardware register
.DEFINE A1B1 $4314              ; Hardware register
.DEFINE DAS1L $4315             ; Hardware register
.DEFINE DAS1H $4316             ; Hardware register
.DEFINE DASB1 $4317             ; Hardware register
.DEFINE A2A1L $4318             ; Hardware register
.DEFINE A2A1H $4319             ; Hardware register
.DEFINE NTRL1 $431A             ; Hardware register
.DEFINE DMAP2 $4320             ; Hardware register
.DEFINE BBAD2 $4321             ; Hardware register
.DEFINE A1T2L $4322             ; Hardware register
.DEFINE A1T2H $4323             ; Hardware register
.DEFINE A1B2 $4324              ; Hardware register
.DEFINE DAS2L $4325             ; Hardware register
.DEFINE DAS2H $4326             ; Hardware register
.DEFINE DASB2 $4327             ; Hardware register
.DEFINE A2A2L $4328             ; Hardware register
.DEFINE A2A2H $4329             ; Hardware register
.DEFINE NTRL2 $432A             ; Hardware register
.DEFINE DMAP3 $4330             ; Hardware register
.DEFINE BBAD3 $4331             ; Hardware register
.DEFINE A1T3L $4332             ; Hardware register
.DEFINE A1T3H $4333             ; Hardware register
.DEFINE A1B3 $4334              ; Hardware register
.DEFINE DAS3L $4335             ; Hardware register
.DEFINE DAS3H $4336             ; Hardware register
.DEFINE DASB3 $4337             ; Hardware register
.DEFINE A2A3L $4338             ; Hardware register
.DEFINE A2A3H $4339             ; Hardware register
.DEFINE NTRL3 $433A             ; Hardware register
.DEFINE DMAP4 $4340             ; Hardware register
.DEFINE BBAD4 $4341             ; Hardware register
.DEFINE A1T4L $4342             ; Hardware register
.DEFINE A1T4H $4343             ; Hardware register
.DEFINE A1B4 $4344              ; Hardware register
.DEFINE DAS4L $4345             ; Hardware register
.DEFINE DAS4H $4346             ; Hardware register
.DEFINE DASB4 $4347             ; Hardware register
.DEFINE A2A4L $4348             ; Hardware register
.DEFINE A2A4H $4349             ; Hardware register
.DEFINE NTRL4 $434A             ; Hardware register
.DEFINE DMAP5 $4350             ; Hardware register
.DEFINE BBAD5 $4351             ; Hardware register
.DEFINE A1T5L $4352             ; Hardware register
.DEFINE A1T5H $4353             ; Hardware register
.DEFINE A1B5 $4354              ; Hardware register
.DEFINE DAS5L $4355             ; Hardware register
.DEFINE DAS5H $4356             ; Hardware register
.DEFINE DASB5 $4357             ; Hardware register
.DEFINE A2A5L $4358             ; Hardware register
.DEFINE A2A5H $4359             ; Hardware register
.DEFINE NTRL5 $435A             ; Hardware register
.DEFINE DMAP6 $4360             ; Hardware register
.DEFINE BBAD6 $4361             ; Hardware register
.DEFINE A1T6L $4362             ; Hardware register
.DEFINE A1T6H $4363             ; Hardware register
.DEFINE A1B6 $4364              ; Hardware register
.DEFINE DAS6L $4365             ; Hardware register
.DEFINE DAS6H $4366             ; Hardware register
.DEFINE DASB6 $4367             ; Hardware register
.DEFINE A2A6L $4368             ; Hardware register
.DEFINE A2A6H $4369             ; Hardware register
.DEFINE NTRL6 $436A             ; Hardware register
.DEFINE DMAP7 $4370             ; Hardware register
.DEFINE BBAD7 $4371             ; Hardware register
.DEFINE A1T7L $4372             ; Hardware register
.DEFINE A1T7H $4373             ; Hardware register
.DEFINE A1B7 $4374              ; Hardware register
.DEFINE DAS7L $4375             ; Hardware register
.DEFINE DAS7H $4376             ; Hardware register
.DEFINE DASB7 $4377             ; Hardware register
.DEFINE A2A7L $4378             ; Hardware register
.DEFINE A2A7H $4379             ; Hardware register
.DEFINE NTRL7 $437A             ; Hardware register

; ----------------------------------------------------------------------------
; __init_start
; 
; ----------------------------------------------------------------------------
__init_start:
    RTS

; ----------------------------------------------------------------------------
; wait_nmi
; Source: /home/nathan/R65/stdlib/sneslib.r65:1597
;   included from examples/hello_world.r65:8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
wait_nmi:
    .ACCU 8
    .INDEX 8
    LDA $4210
    STA $16,S
    JMP.w wait_nmi__L1
wait_nmi__L1:
    JMP.w wait_nmi__L2
wait_nmi__L2:
    LDA $16,S
    AND #$80
    STA $17,S
    CMP #$00
    BNE wait_nmi__L4  ; Branch if not equal
    JMP.w wait_nmi__L5
wait_nmi__L4:
    JMP.w wait_nmi__L3
wait_nmi__L3:
    RTS
wait_nmi__L5:
    JMP.w wait_nmi__L1

; ----------------------------------------------------------------------------
; clear_vram
; Source: /home/nathan/R65/stdlib/sneslib.r65:1620
;   included from examples/hello_world.r65:8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
clear_vram:
    .ACCU 8
    .INDEX 8
    STZ $2116
    STZ $2117
    LDA #$80
    STA $2115
    LDX #$00
    LDY #$00
    JMP.w clear_vram__L1
clear_vram__L1:
    JMP.w clear_vram__L2
clear_vram__L2:
    STZ $2118
    STZ $2119
    INX  ; X++
    CPX #$00
    BEQ clear_vram__L4  ; Branch if equal
    JMP.w clear_vram__L5
clear_vram__L4:
    INY  ; Y++
    CPY #$80
    BEQ clear_vram__L6  ; Branch if equal
    JMP.w clear_vram__L7
clear_vram__L6:
    JMP.w clear_vram__L3
clear_vram__L3:
    RTS
clear_vram__L7:
    JMP.w clear_vram__L5
clear_vram__L5:
    JMP.w clear_vram__L1

; ----------------------------------------------------------------------------
; clear_cgram
; Source: /home/nathan/R65/stdlib/sneslib.r65:1642
;   included from examples/hello_world.r65:8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
clear_cgram:
    .ACCU 8
    .INDEX 8
    STZ $2121
    LDX #$00
    JMP.w clear_cgram__L1
clear_cgram__L1:
    JMP.w clear_cgram__L2
clear_cgram__L2:
    STZ $2122
    STZ $2122
    INX  ; X++
    CPX #$00
    BEQ clear_cgram__L4  ; Branch if equal
    JMP.w clear_cgram__L5
clear_cgram__L4:
    JMP.w clear_cgram__L3
clear_cgram__L3:
    RTS
clear_cgram__L5:
    JMP.w clear_cgram__L1

; ----------------------------------------------------------------------------
; clear_oam
; Source: /home/nathan/R65/stdlib/sneslib.r65:1657
;   included from examples/hello_world.r65:8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
clear_oam:
    .ACCU 8
    .INDEX 8
    STZ $2102
    STZ $2103
    LDX #$00
    JMP.w clear_oam__L1
clear_oam__L1:
    JMP.w clear_oam__L2
clear_oam__L2:
    STZ $2104
    LDA #$F0
    STA $2104
    STZ $2104
    STZ $2104
    INX  ; X++
    CPX #$80
    BEQ clear_oam__L4  ; Branch if equal
    JMP.w clear_oam__L5
clear_oam__L4:
    JMP.w clear_oam__L3
clear_oam__L3:
    LDX #$00
    JMP.w clear_oam__L6
clear_oam__L6:
    JMP.w clear_oam__L7
clear_oam__L7:
    STZ $2104
    INX  ; X++
    CPX #$20
    BEQ clear_oam__L9  ; Branch if equal
    JMP.w clear_oam__L10
clear_oam__L9:
    JMP.w clear_oam__L8
clear_oam__L8:
    RTS
clear_oam__L10:
    JMP.w clear_oam__L6
clear_oam__L5:
    JMP.w clear_oam__L1

; ----------------------------------------------------------------------------
; init_ppu
; Source: /home/nathan/R65/stdlib/sneslib.r65:1686
;   included from examples/hello_world.r65:8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
init_ppu:
    .ACCU 8
    .INDEX 8
    LDA #$80
    STA $2100
    STZ $2101
    STZ $2102
    STZ $2103
    STZ $2105
    STZ $2106
    STZ $2107
    STZ $2108
    STZ $2109
    STZ $210A
    STZ $210B
    STZ $210C
    STZ $210D
    STZ $210D
    STZ $210E
    STZ $210E
    STZ $210F
    STZ $210F
    STZ $2110
    STZ $2110
    STZ $2111
    STZ $2111
    STZ $2112
    STZ $2112
    STZ $2113
    STZ $2113
    STZ $2114
    STZ $2114
    LDA #$80
    STA $2115
    STZ $2116
    STZ $2117
    STZ $211A
    LDA #$01
    STA $211E
    LDA #$01
    STA $211B
    STZ $211B
    STZ $211C
    STZ $211C
    STZ $211D
    STZ $211D
    STZ $211E
    STZ $211F
    STZ $211F
    STZ $2120
    STZ $2120
    STZ $2121
    STZ $2123
    STZ $2124
    STZ $2125
    STZ $2126
    STZ $2127
    STZ $2128
    STZ $2129
    STZ $212A
    STZ $212B
    STZ $212C
    STZ $212D
    STZ $212E
    STZ $212F
    STZ $2130
    STZ $2131
    LDA #$20
    LDA #$40
    LDA #$80
    STA $2132
    STZ $2133
    RTS

; ----------------------------------------------------------------------------
; init_cpu
; Source: /home/nathan/R65/stdlib/sneslib.r65:1758
;   included from examples/hello_world.r65:8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
init_cpu:
    .ACCU 8
    .INDEX 8
    STZ $4200
    STZ $420C
    LDA #$01
    STA $420D
    RTS

; ----------------------------------------------------------------------------
; snes_init
; Source: /home/nathan/R65/stdlib/sneslib.r65:1766
;   included from examples/hello_world.r65:8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
snes_init:
    .ACCU 8
    .INDEX 8
    JSR init_cpu
    JSR init_ppu
    JSR clear_vram
    JSR clear_cgram
    JSR clear_oam
    LDA #$81
    STA $4200
    RTS

; ----------------------------------------------------------------------------
; main
; Source: examples/hello_world.r65:122
; 
; Returns: !
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; Entry: true
; ----------------------------------------------------------------------------
main:
    .ACCU 8
    .INDEX 8
SEI
CLC
XCE
    JSR __init_start
    JSR snes_init
    STZ $2105
    STZ $2107
    LDA #$01
    STA $210B
    LDA #$80
    STA $2115
    JSR upload_font
    JSR write_message
    JSR upload_palette
    LDA #$01
    STA $212C
    LDA #$0F
    STA $2100
    JMP.w main__L1
main__L1:
    JMP.w main__L2
main__L2:
    JSR wait_nmi
    JMP.w main__L1

; ----------------------------------------------------------------------------
; upload_font
; Source: examples/hello_world.r65:161
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
upload_font:
    .ACCU 8
    .INDEX 8
    LDA #$00
    STA $2116
    LDA #$10
    STA $16,S
    STA $2117
    LDX #$00
    JMP.w upload_font__L1
upload_font__L1:
    JMP.w upload_font__L2
upload_font__L2:
    LDA.w __FONT_data,X
    STA $16,S
    STA $2118
    STA $2119
    INX  ; X++
    CPX #$D8
    BEQ upload_font__L4  ; Branch if equal
    JMP.w upload_font__L5
upload_font__L4:
    JMP.w upload_font__L3
upload_font__L3:
    RTS
upload_font__L5:
    JMP.w upload_font__L1

; ----------------------------------------------------------------------------
; write_message
; Source: examples/hello_world.r65:191
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
write_message:
    .ACCU 8
    .INDEX 8
    LDA #$CA
    STA $2116
    LDA #$01
    STA $16,S
    STA $2117
    LDX #$00
    JMP.w write_message__L1
write_message__L1:
    JMP.w write_message__L2
write_message__L2:
    LDA.w __MESSAGE_data,X
    STA $16,S
    CMP #$00
    BEQ write_message__L4  ; Branch if equal
    JMP.w write_message__L5
write_message__L4:
    JMP.w write_message__L3
write_message__L3:
    RTS
write_message__L5:
    JSR ascii_to_tile
    STA $16,S
    STA $2118
    STZ $2119
    INX  ; X++
    JMP.w write_message__L1

; ----------------------------------------------------------------------------
; ascii_to_tile
; Source: examples/hello_world.r65:222
; 
; Parameters:
;   char: u8
; 
; Returns: u8
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
ascii_to_tile:
    .ACCU 8
    .INDEX 8
    CMP #$20
    BEQ ascii_to_tile__L1  ; Branch if equal
    JMP.w ascii_to_tile__L3
ascii_to_tile__L1:
    LDA #$00
    JMP.w ascii_to_tile__L2
ascii_to_tile__L2:
    RTS
ascii_to_tile__L3:
    SEC
    SBC #$40
    JMP.w ascii_to_tile__L2

; ----------------------------------------------------------------------------
; upload_palette
; Source: examples/hello_world.r65:238
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; ----------------------------------------------------------------------------
upload_palette:
    .ACCU 8
    .INDEX 8
    STZ $2121
    LDX #$00
    JMP.w upload_palette__L1
upload_palette__L1:
    JMP.w upload_palette__L2
upload_palette__L2:
    LDA.w __PALETTE_data,X
    STA $16,S
    STA $2122
    INX  ; X++
    CPX #$08
    BEQ upload_palette__L4  ; Branch if equal
    JMP.w upload_palette__L5
upload_palette__L4:
    JMP.w upload_palette__L3
upload_palette__L3:
    RTS
upload_palette__L5:
    JMP.w upload_palette__L1

; ============================================================================
; ROM Data Sections (array literal init data)
; ============================================================================
__MESSAGE_data:
.db $48, $45, $4C, $4C, $4F, $20, $57, $4F, $52, $4C, $44, $00
__FONT_data:
.db $00, $00, $00, $00, $00, $00, $00, $00, $18, $3C, $66, $66, $7E, $66, $66, $00
.db $7C, $66, $66, $7C, $66, $66, $7C, $00, $3C, $66, $60, $60, $60, $66, $3C, $00
.db $78, $6C, $66, $66, $66, $6C, $78, $00, $7E, $60, $60, $7C, $60, $60, $7E, $00
.db $7E, $60, $60, $7C, $60, $60, $60, $00, $3C, $66, $60, $6E, $66, $66, $3E, $00
.db $66, $66, $66, $7E, $66, $66, $66, $00, $3C, $18, $18, $18, $18, $18, $3C, $00
.db $1E, $0C, $0C, $0C, $0C, $6C, $38, $00, $66, $6C, $78, $70, $78, $6C, $66, $00
.db $60, $60, $60, $60, $60, $60, $7E, $00, $63, $77, $7F, $6B, $63, $63, $63, $00
.db $66, $76, $7E, $7E, $6E, $66, $66, $00, $3C, $66, $66, $66, $66, $66, $3C, $00
.db $7C, $66, $66, $7C, $60, $60, $60, $00, $3C, $66, $66, $66, $6A, $6C, $36, $00
.db $7C, $66, $66, $7C, $6C, $66, $66, $00, $3C, $66, $60, $3C, $06, $66, $3C, $00
.db $7E, $18, $18, $18, $18, $18, $18, $00, $66, $66, $66, $66, $66, $66, $3C, $00
.db $66, $66, $66, $66, $66, $3C, $18, $00, $63, $63, $63, $6B, $7F, $77, $63, $00
.db $66, $66, $3C, $18, $3C, $66, $66, $00, $66, $66, $66, $3C, $18, $18, $18, $00
.db $7E, $06, $0C, $18, $30, $60, $7E, $00
__PALETTE_data:
.db $00, $00, $29, $25, $52, $4A, $FF, $7F
__empty_handler:
    RTI

; ============================================================================
; SNES ROM Header
; ============================================================================
.SNESHEADER
ID "SNES"
NAME "R65 Compiled ROM     "
LOROM
CARTRIDGETYPE $00
ROMSIZE $08
SRAMSIZE $00
COUNTRY $01
LICENSEECODE $00
VERSION $00
.ENDSNES

; ============================================================================
; Interrupt Vectors (Native Mode)
; ============================================================================
.SNESNATIVEVECTOR
COP __empty_handler
BRK __empty_handler
ABORT __empty_handler
NMI __empty_handler
IRQ __empty_handler
.ENDNATIVEVECTOR

; ============================================================================
; Interrupt Vectors (Emulation Mode)
; ============================================================================
.SNESEMUVECTOR
COP __empty_handler
ABORT __empty_handler
NMI __empty_handler
RESET main
IRQBRK __empty_handler
.ENDEMUVECTOR
