; ============================================================================
; Generated by R65 Compiler
; ============================================================================
; Source: <unknown>
; Generated: 2026-01-02 07:08:22
; Compiler Version: 0.1.0
; ============================================================================

.65816

; ============================================================================
; Memory Map (LOROM)
; ============================================================================
.MEMORYMAP
    DEFAULTSLOT 0
    SLOTSIZE $8000
    SLOT 0 $8000
.ENDME

.ROMBANKMAP
    BANKSTOTAL 1
    BANKSIZE $8000
    BANKS 1
.ENDRO

; ============================================================================
; Direct Page Allocations
; ============================================================================
.DEFINE counter $0020           ; Explicit

; ----------------------------------------------------------------------------
; __init_start
; 
; ----------------------------------------------------------------------------
__init_start:
    LDA #$00
    STA $20
    RTS

; ----------------------------------------------------------------------------
; main
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.NONE: 'none'>)
; Entry: true
; ----------------------------------------------------------------------------
main:
    JSR __init_start
    LDA #$00
    STA $20
    RTS

; ----------------------------------------------------------------------------
; vblank_handler
; 
; Mode: ModeAttribute(name='mode', source_loc=None, m_mode=<MMode.M8: 'm8'>, x_mode=<XMode.X8: 'x8'>, transition=<ModeTransition.AUTO: 'auto'>)
; ----------------------------------------------------------------------------
vblank_handler:
    PHP
    PHA
    PHX
    PHY
    PHD
    PHB
    SEP #$30
    LDA $20
    STA $16
    LDA $16
    CLC
    ADC #$01
    STA $17
    LDA $17
    STA $20
    PLB
    PLD
    PLY
    PLX
    PLA
    PLP
    RTI

; ============================================================================
; Interrupt Vectors (Native Mode)
; ============================================================================
.ORGA $FFE4
    .dw 0                       ; COP
    .dw 0                       ; BRK
    .dw 0                       ; ABORT
    .dw vblank_handler          ; NMI
    .dw 0                       ; (unused)
    .dw 0                       ; IRQ

; ============================================================================
; Interrupt Vectors (Emulation Mode)
; ============================================================================
.ORGA $FFF4
    .dw 0                       ; COP
    .dw 0                       ; (unused)
    .dw 0                       ; ABORT
    .dw 0                       ; NMI
    .dw main                    ; RESET
    .dw 0                       ; IRQ/BRK

; ============================================================================
; Symbol Exports
; ============================================================================
.EXPORT __init_start
.EXPORT main
.EXPORT vblank_handler
