"""
Extract per-function assembly from R65 compiler output.

The compiler emits WLA-DX assembly with function blocks delimited by
comment headers like:

    ; ----------------------------------------------------------------------------
    ; func_name
    ; Source: file:line
    ; ...
    ; ----------------------------------------------------------------------------
    func_name:
        instructions...
"""

import re


# Functions generated by the compiler that aren't user code
_COMPILER_GENERATED = frozenset({
    '__init_start',
    '__empty_handler',
    '__vectors',
    '__reset',
})

# Pattern matching the separator line: "; -----...-----"
_SEPARATOR_RE = re.compile(r'^; -{10,}$')

# Pattern matching a function name comment: "; func_name"
_FUNC_COMMENT_RE = re.compile(r'^; (\w+)\s*$')


def extract_function_asm(full_asm: str, func_name: str) -> str | None:
    """Extract assembly for a single function from full compiler output.

    Returns the assembly text from the function label through to the next
    section separator or section header, or None if the function is not found.
    """
    lines = full_asm.split('\n')
    in_func = False
    func_lines: list[str] = []

    for line in lines:
        if line.strip() == f'{func_name}:':
            in_func = True
            func_lines.append(line)
        elif in_func:
            stripped = line.strip()
            # Stop at next function separator block or section header
            if _SEPARATOR_RE.match(stripped) and func_lines:
                break
            # Stop at ROM data sections or other major delimiters
            if stripped.startswith('; ====') and func_lines:
                break
            func_lines.append(line)

    if not func_lines:
        return None
    # Trim trailing blank lines
    while func_lines and not func_lines[-1].strip():
        func_lines.pop()
    return '\n'.join(func_lines)


def extract_all_functions(full_asm: str) -> dict[str, str]:
    """Extract all user-defined functions from compiler output.

    Returns dict mapping function name -> assembly text (from label to next separator).
    Skips compiler-generated functions (__init_start, __empty_handler, etc).
    """
    functions: dict[str, str] = {}
    lines = full_asm.split('\n')

    # Strategy: find all "label:" lines, then grab from label to next separator
    # First, identify function labels by finding the comment header pattern
    func_labels: list[str] = []
    i = 0
    while i < len(lines):
        stripped = lines[i].strip()
        # Look for separator followed by "; funcname" on next line
        if _SEPARATOR_RE.match(stripped) and i + 1 < len(lines):
            name_match = _FUNC_COMMENT_RE.match(lines[i + 1].strip())
            if name_match:
                func_labels.append(name_match.group(1))
        i += 1

    # Now extract each function's assembly
    for func_name in func_labels:
        if func_name in _COMPILER_GENERATED:
            continue
        asm = extract_function_asm(full_asm, func_name)
        if asm is not None:
            functions[func_name] = asm

    return functions


def instruction_lines(asm: str) -> list[str]:
    """Extract only instruction lines from assembly text.

    Strips labels, directives (lines starting with .), comments, and blank lines.
    Returns cleaned instruction mnemonics.
    """
    result: list[str] = []
    for line in asm.split('\n'):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith(';'):
            continue
        if stripped.startswith('.'):
            continue
        if stripped.endswith(':'):
            continue
        # Strip inline comments
        if ';' in stripped:
            stripped = stripped[:stripped.index(';')].rstrip()
        if stripped:
            result.append(stripped)
    return result


def get_function_source(r65_source: str, func_name: str) -> str | None:
    """Extract R65 source code for a specific function.

    Does basic brace-matching to find the function body.
    Returns the full function text including signature, or None if not found.

    Handles mangled trait method names like 'U32__add' by searching for 'fn add('
    inside the source.
    """
    lines = r65_source.split('\n')

    # Try exact name first, then demangle trait method names (Type__method -> method)
    names_to_try = [func_name]
    if '__' in func_name:
        # U32__add -> add, I32__from_i16 -> from_i16
        demangled = func_name.split('__', 1)[1]
        names_to_try.append(demangled)

    for name in names_to_try:
        pattern = re.compile(rf'\bfn\s+{re.escape(name)}\s*\(')

        start_idx = None
        for i, line in enumerate(lines):
            if pattern.search(line):
                start_idx = i
                break

        if start_idx is not None:
            break

    if start_idx is None:
        return None

    # Include preceding attribute lines (#[...])
    attr_start = start_idx
    while attr_start > 0 and lines[attr_start - 1].strip().startswith('#['):
        attr_start -= 1

    # Brace-match to find function end
    brace_depth = 0
    found_open = False

    for i in range(start_idx, len(lines)):
        for ch in lines[i]:
            if ch == '{':
                brace_depth += 1
                found_open = True
            elif ch == '}':
                brace_depth -= 1
                if found_open and brace_depth == 0:
                    return '\n'.join(lines[attr_start:i + 1])

    # If no closing brace found, return from start to end
    return '\n'.join(lines[attr_start:])
